### ISSUE TITLE
pio train error

### ISSUE THREAD

**Issue by phiripatrick663** [andrewwuan/PredictionIO-Churn-Prediction-H2O-Sparkling-Water#2]
I followed steps as decsribed but am getting an error during pio train. I did not see a thread in predictionio forum, so came here to leave comment.

My error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/ExistingRdd
   at com.mycompany.Algorithm.train(Algorithm.scala:28)
   ...plus more

In engine.json I only changed appID parameter. Was there more to change?

Thanks.
Patrick

**Comment by indrekots** [comment]
I encountered the same exception by following the steps described on the template page (https://templates.prediction.io/andrewwuan/PredictionIO-Churn-Prediction-H2O-Sparkling-Water)

**Comment by phiripatrick663** [comment]
I am not sure if Andrew is aware there are posts here. He has not been active for a while now. Hopefully he checks this post and give us more clarity.

**Comment by andrewwuan** [comment]
@phiripatrick663 @indrekots This is due to that old sparkling water library doesn't support Spark version from 1.3 onward. I've just made a new release for my template `v0.1.2` and it should resolve this error.

**Comment by indrekots** [comment]
Now it works as expected. Thanks!

**Comment by phiripatrick663** [comment]
Thanks for the response Andrew, I will download new version and give feedback.

If you don't mind could you give more specific steps on running the example and what I should expect as a successful result?

**Comment by phiripatrick663** [comment]
I don't see where to edit my engine.json. File looks different from other engine.json files. Any help please.

**Comment by andrewwuan** [comment]
@phiripatrick663 Replace `INVALID_APPNAME` with your app name (instead of app ID as before).

**Comment by phiripatrick663** [comment]
I guess my engine.json is not importing correctly.  I am getting
"com.mycompany" repeated through out, that's why I did not see where to
make changes.  It does not look like the normal .json structure. Where
could this be coming from?
Thanks.

**Comment by andrewwuan** [comment]
I'm not sure. But checking the template in my repo might help: https://github.com/andrewwuan/PredictionIO-Churn-Prediction-H2O-Sparkling-Water/blob/master/engine.json

**Comment by phiripatrick663** [comment]
Ok,  l may just download that one and post an image of the other one so you
can see what I am seeing.
Thanks.

**Comment by phiripatrick663** [comment]
Hi Andrew,
Happy to report that template ran without errors. I do need a little assistance though, I have no idea what to expect as a result of the trial query. At first I was not sure how to query it, but made the query into a python file, made it executable and ran. Is that the correct way? Can you give an example of expected result?

Thanks.
