### ISSUE TITLE
template result

### ISSUE THREAD

**Issue by phiripatrick663** [andrewwuan/PredictionIO-Churn-Prediction-H2O-Sparkling-Water#3]
Hi Andrew,
Happy to report that the new version template ran without errors. I do need a little assistance though, I have no idea what to expect as a result of the trial query. At first I was not sure how to query it, but made the query into a python file, made it executable and ran. Is that the correct way? Can you give an example of expected result? Any further suggestions on use and customizing template?

Thanks.

**Comment by andrewwuan** [comment]
@phiripatrick663 If you look at README.md, putting the query in a python file and running it is indeed the correct way. An example query would be (copying from README.md):

```
engine_client.send_query({'intlPlan': True, 'voiceMailPlan': True, 'numVmailMsg': 41, 'totalDayMins': 173.1, 
    'totalDayCalls': 85, 'totalDayCharge': 29.43, 'totalEveMins': 203.9, 'totalEveCalls': 107, 
    'totalEveCharge': 17.33, 'totalNightMins': 122.2, 'totalNightCalls': 78, 'totalNightCharge': 14.02, 
    'totalIntlMins': 10.0, 'totalIntlCalls': 15, 'totalIntlCharge': 3.94, 'customerServiceCalls': 0})
```

You can configure the set of arguments you provide by modifying `Engine.scala` and `Algorithm.scala`. I don't have a specific expected result, but generally, if you have a query that contains what's "like" the imported data, the output percentage will be higher, and vice versa.

**Comment by phiripatrick663** [comment]
Thanks Andrew. I will play around with customizing those two files and wee what I can post as success.

**Comment by andrewwuan** [comment]
:+1:
